[package]
name = "sub-du"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "A du-like tool for reading storage size of Substrate chains."

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.22", features = [
	"jsonrpsee-http-client",
	"jsonrpsee-types",
	"jsonrpsee-ws-client",
] }
separator = "0.4.1"
ansi_term = "0.12.1"
tracing-subscriber = "0.3.16"
log = "0.4.17"
structopt = "0.3"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }

sp-core = { path = "../../../primitives/core" }
sp-runtime = { path = "../../../primitives/runtime" }
frame-metadata = { version = "16.0.0", default-features = false, features = [
	"current",
	"std",
] }
sc-rpc-api = { path = "../../../client/rpc-api" }
substrate-rpc-client = { path = "../rpc/client" }

[dev-dependencies]
assert_cmd = "2"

[features]
default = []
remote-test-kusama = []
remote-test-polkadot = []
