[package]
name = "sub-du"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.15.1", features = ["jsonrpsee-types", "jsonrpsee-http-client", "jsonrpsee-ws-client"] }
separator = "0.4.1"
ansi_term = "0.12.1"
tracing-subscriber = "0.3.16"
log = "0.4.17"
structopt = "0.3"
tokio = { version = "1.21.2", features = ["rt-multi-thread", "macros"]}

remote-externalities = { path = "../remote-externalities" }
sp-runtime = { version = "6.0.0", path = "../../../primitives/runtime" }
frame-metadata = { version = "15.0.0", default-features = false, features = ["v14", "std"] }
sc-rpc-api = { version = "0.10.0-dev", path = "../../../client/rpc-api" }

[features]
default = []
remote-test-kusama = []
remote-test-polkadot = []

[dev-dependencies]
assert_cmd = "2"